package com.slender.forumbackend.constant.core

object Message {
    object User {
        const val CAPTCHA_SENT = "验证码已发送"
        const val LOGIN_SUCCESS = "登录成功"
        const val LOGOUT_SUCCESS = "退出登录成功"
        const val REGISTER_SUCCESS = "注册成功"
    }

    object Exception {
        const val ALREADY_CHECKED_IN_ERROR = "今日已签到"
        const val ANNOUNCEMENT_NOT_FOUND_ERROR = "公告不存在"
        const val ACCESS_TOKEN_EXPIRE_ERROR = "访问令牌已过期"
        const val AUTHORITY_ERROR = "权限不足"
        const val BLOCK_ERROR = "用户已被封禁"
        const val CAPTCHA_INVALID_ERROR = "验证码错误或已过期"
        const val EMAIL_OR_PASSWORD_ERROR = "邮箱或密码错误"
        const val EMAIL_REGISTERED_ERROR = "邮箱已注册"
        const val INTERNAL_ERROR = "服务器内部错误"
        const val LOGIN_ERROR = "登录失败"
        const val REFRESH_TOKEN_EXPIRE_ERROR = "刷新令牌已过期"
        const val REQUEST_READ_ERROR = "请求内容读取失败"
        const val REQUEST_CONTENT_ERROR = "请求内容错误"
        const val TOKEN_NOT_FOUND = "令牌不存在"
        const val TOKEN_SIGNATURE_ERROR = "令牌签名错误"
        const val UNKNOWN_ERROR = "认证失败"
        const val USER_NOT_FOUND_ERROR = "用户不存在"
        const val ARTICLE_NOT_FOUND_ERROR = "文章不存在"
        const val ARTICLE_FORBIDDEN_ERROR = "文章不可见"
        const val ARTICLE_CONTENT_INVALID_ERROR = "标题或正文不合法"
        const val ARTICLE_ALREADY_REWARDED_ERROR = "已打赏过该文章"
        const val MOE_POINT_NOT_ENOUGH_ERROR = "萌萌点不足"
        const val ARTICLE_TAG_INVALID_ERROR = "标签不存在或数量超限"
        const val COMMENT_NOT_FOUND_ERROR = "评论不存在"
        const val COMMENT_CONTENT_INVALID_ERROR = "评论内容不合法"
        const val COMMENT_DEPTH_EXCEEDED_ERROR = "回复层级超限"
        const val COMMENT_FORBIDDEN_ERROR = "无权操作该评论"
        const val FILE_NOT_FOUND_ERROR = "文件不存在"
        const val FILE_NAME_INVALID_ERROR = "文件名为空或格式错误"
        const val IMAGE_EMPTY_ERROR = "文件不能为空"
        const val IMAGE_TOO_LARGE_ERROR = "文件大小超过10MB限制"
        const val IMAGE_TYPE_UNSUPPORTED_ERROR = "不支持的文件类型,仅支持png/jpeg/webp/gif"
        const val IMAGE_COUNT_INVALID_ERROR = "文件数量必须在1-9之间"
        const val UPLOAD_ITEM_FAILED_ERROR = "上传失败"
        const val UPLOAD_TOO_LARGE_ERROR = "文件超过大小上限"
        const val UPLOAD_TYPE_UNSUPPORTED_ERROR = "不支持的文件类型"
        const val UPLOAD_FAILED_ERROR = "存储失败"
        const val REPORT_DUPLICATED_ERROR = "重复举报"
        const val REPORT_REASON_INVALID_ERROR = "举报理由不合法"
        const val RATE_LIMITED_ERROR = "操作过于频繁"
        const val CONVERSATION_NOT_FOUND_ERROR = "会话不存在"
        const val MESSAGE_SEND_FAILED_ERROR = "消息发送失败"
        const val MESSAGE_TARGET_INVALID_ERROR = "对方不存在或拒收"
        const val CONVERSATION_FOLLOW_REQUIRED_ERROR = "请先关注该用户后再私聊"
        const val ADMIN_RESOURCE_NOT_FOUND_ERROR = "后台资源不存在"
    }
}
