spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  config:
    import: optional:file:./.env[.properties]
  application:
    name: ForumBackEnd
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: slender
    password: 123456
  data:
    redis:
      lettuce:
        pool:
          max-wait: 1000
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 465
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
forum:
  archive:
    retention-days: 30
    cron: "0 0 3 * * *"
    batch-size: 500
  oss:
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      insert-ignore-auto-increment-column: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /openapi/swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  writer-with-default-pretty-printer: true
