CREATE TABLE users (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar VARCHAR(1024) NOT NULL,
    gender VARCHAR(16) NOT NULL DEFAULT 'Unknown',
    signature VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_gender CHECK (gender IN ('Male', 'Female', 'Unknown')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'BANNED', 'DELETED'))
);

CREATE TABLE user_stats (
    user_id BIGINT PRIMARY KEY,
    fan_count INTEGER NOT NULL DEFAULT 0,
    follow_count INTEGER NOT NULL DEFAULT 0,
    published_article_count INTEGER NOT NULL DEFAULT 0,
    liked_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_user_stats_fan_count CHECK (fan_count >= 0),
    CONSTRAINT ck_user_stats_follow_count CHECK (follow_count >= 0),
    CONSTRAINT ck_user_stats_published_article_count CHECK (published_article_count >= 0),
    CONSTRAINT ck_user_stats_liked_count CHECK (liked_count >= 0)
);

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(64) NOT NULL,
    resource VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    description VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_permissions_code UNIQUE (code)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE tags (
    tid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tags_name UNIQUE (name)
);

CREATE TABLE articles (
    article_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(512) NOT NULL,
    cover VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    publish_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revise_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_articles_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'DELETED')),
    CONSTRAINT ck_articles_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE', 'FOLLOWERS'))
);

CREATE TABLE article_contents (
    article_id BIGINT PRIMARY KEY,
    content TEXT NOT NULL
);

CREATE TABLE article_stats (
    article_id BIGINT PRIMARY KEY,
    like_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_article_stats_like_count CHECK (like_count >= 0),
    CONSTRAINT ck_article_stats_comment_count CHECK (comment_count >= 0),
    CONSTRAINT ck_article_stats_view_count CHECK (view_count >= 0)
);

CREATE TABLE article_promotions (
    promotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    promoter_id BIGINT NOT NULL,
    content VARCHAR(512) NOT NULL,
    promote_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE article_reactions (
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    emoji VARCHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, user_id, emoji)
);

CREATE TABLE article_likes (
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, user_id)
);

CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    root_comment_id BIGINT NOT NULL DEFAULT 0,
    parent_comment_id BIGINT NOT NULL DEFAULT 0,
    reply_to_user_id BIGINT NOT NULL DEFAULT 0,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    publish_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_comments_status CHECK (status IN ('NORMAL', 'DELETED')),
    CONSTRAINT ck_comments_reply_shape CHECK (
        (root_comment_id = 0 AND parent_comment_id = 0 AND reply_to_user_id = 0)
        OR
        (root_comment_id > 0 AND parent_comment_id > 0)
    )
);

CREATE TABLE comment_stats (
    comment_id BIGINT PRIMARY KEY,
    like_count INTEGER NOT NULL DEFAULT 0,
    reply_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_comment_stats_like_count CHECK (like_count >= 0),
    CONSTRAINT ck_comment_stats_reply_count CHECK (reply_count >= 0)
);

CREATE TABLE comment_likes (
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE article_tags (
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, tag_id)
);

CREATE TABLE user_tags (
    user_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, tag_id)
);

CREATE TABLE user_follows (
    follower_id BIGINT NOT NULL,
    followee_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (follower_id, followee_id),
    CONSTRAINT ck_user_follows_not_self CHECK (follower_id <> followee_id)
);

CREATE INDEX idx_articles_author_id ON articles (author_id);
CREATE INDEX idx_articles_status_publish_time ON articles (status, publish_time);
CREATE INDEX idx_article_promotions_article_id ON article_promotions (article_id);
CREATE INDEX idx_article_promotions_promoter_id ON article_promotions (promoter_id);
CREATE INDEX idx_article_reactions_article_emoji ON article_reactions (article_id, emoji);
CREATE INDEX idx_article_likes_user_id ON article_likes (user_id);
CREATE INDEX idx_comments_article_root_publish_time ON comments (article_id, root_comment_id, publish_time);
CREATE INDEX idx_comments_author_id ON comments (author_id);
CREATE INDEX idx_comment_likes_user_id ON comment_likes (user_id);
CREATE INDEX idx_article_tags_tag_id ON article_tags (tag_id);
CREATE INDEX idx_user_tags_tag_id ON user_tags (tag_id);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);
CREATE INDEX idx_user_follows_followee_id ON user_follows (followee_id);

INSERT INTO roles (code, name, description) VALUES
    ('ADMIN', 'Administrator', 'Full system administrator'),
    ('MODERATOR', 'Moderator', 'Forum content moderator'),
    ('USER', 'User', 'Registered forum user');

INSERT INTO permissions (code, name, resource, action, description) VALUES
    ('article:create', 'Create article', 'article', 'create', 'Create own articles'),
    ('article:update:own', 'Update own article', 'article', 'update_own', 'Update own articles'),
    ('article:update:any', 'Update any article', 'article', 'update_any', 'Update any article'),
    ('article:delete:own', 'Delete own article', 'article', 'delete_own', 'Delete own articles'),
    ('article:delete:any', 'Delete any article', 'article', 'delete_any', 'Delete any article'),
    ('article:audit', 'Audit article', 'article', 'audit', 'Audit article publication'),
    ('comment:create', 'Create comment', 'comment', 'create', 'Create comments'),
    ('comment:delete:own', 'Delete own comment', 'comment', 'delete_own', 'Delete own comments'),
    ('comment:delete:any', 'Delete any comment', 'comment', 'delete_any', 'Delete any comment'),
    ('user:ban', 'Ban user', 'user', 'ban', 'Ban or unban users'),
    ('user:assign-role', 'Assign role', 'user', 'assign_role', 'Assign roles to users'),
    ('system:manage', 'Manage system', 'system', 'manage', 'Manage system settings');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'ADMIN';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.code IN (
    'article:update:any',
    'article:delete:any',
    'article:audit',
    'comment:delete:any',
    'user:ban'
)
WHERE r.code = 'MODERATOR';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.code IN (
    'article:create',
    'article:update:own',
    'article:delete:own',
    'comment:create',
    'comment:delete:own'
)
WHERE r.code = 'USER';
