CREATE TABLE users (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar VARCHAR(1024) NOT NULL,
    gender VARCHAR(16) NOT NULL DEFAULT 'Unknown',
    signature VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    level INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_gender CHECK (gender IN ('Male', 'Female', 'Unknown')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'BANNED', 'DELETED')),
    CONSTRAINT ck_users_level CHECK (level >= 0 AND level <= 6)
);

CREATE TABLE user_stats (
    user_id BIGINT PRIMARY KEY,
    fan_count INTEGER NOT NULL DEFAULT 0,
    follow_count INTEGER NOT NULL DEFAULT 0,
    published_article_count INTEGER NOT NULL DEFAULT 0,
    liked_count INTEGER NOT NULL DEFAULT 0,
    moe_point INTEGER NOT NULL DEFAULT 0,
    promoted_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_user_stats_fan_count CHECK (fan_count >= 0),
    CONSTRAINT ck_user_stats_follow_count CHECK (follow_count >= 0),
    CONSTRAINT ck_user_stats_published_article_count CHECK (published_article_count >= 0),
    CONSTRAINT ck_user_stats_liked_count CHECK (liked_count >= 0),
    CONSTRAINT ck_user_stats_moe_point CHECK (moe_point >= 0),
    CONSTRAINT ck_user_stats_promoted_count CHECK (promoted_count >= 0)
);

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(64) NOT NULL,
    resource VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    description VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_permissions_code UNIQUE (code)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE tags (
    tid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    color INTEGER NOT NULL DEFAULT -1,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tags_name_color UNIQUE (name, color)
);

CREATE TABLE articles (
    article_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(512) NOT NULL,
    cover VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    publish_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revise_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_articles_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'DELETED')),
    CONSTRAINT ck_articles_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE', 'FOLLOWERS'))
);

CREATE TABLE article_contents (
    article_id BIGINT PRIMARY KEY,
    content TEXT NOT NULL
);

CREATE TABLE article_stats (
    article_id BIGINT PRIMARY KEY,
    like_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    reward_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_article_stats_like_count CHECK (like_count >= 0),
    CONSTRAINT ck_article_stats_comment_count CHECK (comment_count >= 0),
    CONSTRAINT ck_article_stats_view_count CHECK (view_count >= 0),
    CONSTRAINT ck_article_stats_reward_count CHECK (reward_count >= 0)
);

CREATE TABLE article_promotions (
    promotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    promoter_id BIGINT NOT NULL,
    content VARCHAR(512) NOT NULL,
    promote_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE article_reactions (
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    emoji VARCHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, user_id)
);

CREATE TABLE article_likes (
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, user_id)
);

CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    root_comment_id BIGINT NOT NULL DEFAULT 0,
    parent_comment_id BIGINT NOT NULL DEFAULT 0,
    reply_to_user_id BIGINT NOT NULL DEFAULT 0,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    publish_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_comments_status CHECK (status IN ('NORMAL', 'DELETED')),
    CONSTRAINT ck_comments_reply_shape CHECK (
        (root_comment_id = 0 AND parent_comment_id = 0 AND reply_to_user_id = 0)
        OR
        (root_comment_id > 0 AND parent_comment_id > 0)
    )
);

CREATE TABLE comment_stats (
    comment_id BIGINT PRIMARY KEY,
    like_count INTEGER NOT NULL DEFAULT 0,
    reply_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_comment_stats_like_count CHECK (like_count >= 0),
    CONSTRAINT ck_comment_stats_reply_count CHECK (reply_count >= 0)
);

CREATE TABLE comment_likes (
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE article_tags (
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, tag_id)
);

CREATE TABLE user_tags (
    user_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, tag_id)
);

CREATE TABLE user_follows (
    follower_id BIGINT NOT NULL,
    followee_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (follower_id, followee_id),
    CONSTRAINT ck_user_follows_not_self CHECK (follower_id <> followee_id)
);

CREATE TABLE comment_reactions (
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    emoji VARCHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE article_rewards (
    reward_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_article_rewards_amount CHECK (amount > 0)
);

CREATE TABLE reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    reason VARCHAR(64) NOT NULL,
    detail VARCHAR(512) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reports_target_type CHECK (target_type IN ('ARTICLE', 'COMMENT', 'USER')),
    CONSTRAINT ck_reports_reason CHECK (reason IN ('Spam', 'Pornography', 'Abuse', 'Infringement', 'Illegal', 'Other')),
    CONSTRAINT ck_reports_status CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED'))
);

CREATE TABLE conversations (
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_1 BIGINT NOT NULL,
    user_id_2 BIGINT NOT NULL,
    last_message_id BIGINT,
    last_message_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_conversations_user_order CHECK (user_id_1 < user_id_2)
);

CREATE TABLE messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    client_message_id VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'SENT',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_messages_status CHECK (status IN ('SENT', 'DELETED'))
);

CREATE TABLE conversation_reads (
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_message_id BIGINT NOT NULL,
    last_read_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE comment_notices (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_comment_notices_type CHECK (type IN ('COMMENT', 'REPLY'))
);

CREATE TABLE favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE carousels (
    carousel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(512) NOT NULL,
    image VARCHAR(1024) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_value VARCHAR(512) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_carousels_target_type CHECK (target_type IN ('Article', 'Url', 'None'))
);

CREATE INDEX idx_articles_author_id ON articles (author_id);
CREATE INDEX idx_articles_status_publish_time ON articles (status, publish_time);
CREATE INDEX idx_article_promotions_article_id ON article_promotions (article_id);
CREATE INDEX idx_article_promotions_promoter_id ON article_promotions (promoter_id);
CREATE INDEX idx_article_reactions_article_emoji ON article_reactions (article_id, emoji);
CREATE INDEX idx_article_likes_user_id ON article_likes (user_id);
CREATE INDEX idx_comments_article_root_publish_time ON comments (article_id, root_comment_id, publish_time);
CREATE INDEX idx_comments_author_id ON comments (author_id);
CREATE INDEX idx_comment_likes_user_id ON comment_likes (user_id);
CREATE INDEX idx_article_tags_tag_id ON article_tags (tag_id);
CREATE INDEX idx_user_tags_tag_id ON user_tags (tag_id);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);
CREATE INDEX idx_user_follows_followee_id ON user_follows (followee_id);
CREATE INDEX idx_comment_reactions_comment_emoji ON comment_reactions (comment_id, emoji);
CREATE INDEX idx_article_rewards_article_id ON article_rewards (article_id);
CREATE INDEX idx_article_rewards_user_id ON article_rewards (user_id);
CREATE UNIQUE INDEX uk_article_rewards_article_user ON article_rewards (article_id, user_id);
CREATE INDEX idx_reports_reporter_id ON reports (reporter_id);
CREATE INDEX idx_reports_target ON reports (target_type, target_id);
CREATE UNIQUE INDEX uk_reports_reporter_target ON reports (reporter_id, target_type, target_id);
CREATE UNIQUE INDEX uk_conversations_users ON conversations (user_id_1, user_id_2);
CREATE INDEX idx_conversations_user1_time ON conversations (user_id_1, last_message_time);
CREATE INDEX idx_conversations_user2_time ON conversations (user_id_2, last_message_time);
CREATE INDEX idx_messages_conversation_time ON messages (conversation_id, create_time);
CREATE INDEX idx_messages_sender_id ON messages (sender_id);
CREATE UNIQUE INDEX uk_messages_sender_client
    ON messages (sender_id, client_message_id)
    WHERE client_message_id IS NOT NULL AND client_message_id <> '';
CREATE INDEX idx_conversation_reads_user_id ON conversation_reads (user_id);
CREATE INDEX idx_comment_notices_recipient_time ON comment_notices (recipient_id, create_time);
CREATE INDEX idx_comment_notices_comment_id ON comment_notices (comment_id);
CREATE UNIQUE INDEX uk_favorites_user_article ON favorites (user_id, article_id);
CREATE INDEX idx_favorites_article_id ON favorites (article_id);
CREATE INDEX idx_carousels_enabled_sort ON carousels (enabled, sort_order);
