CREATE TABLE image_assets (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    byte_size BIGINT NOT NULL,
    type VARCHAR(16) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_image_assets_object_key UNIQUE (object_key),
    CONSTRAINT ck_image_assets_width CHECK (width > 0),
    CONSTRAINT ck_image_assets_height CHECK (height > 0),
    CONSTRAINT ck_image_assets_byte_size CHECK (byte_size > 0)
);

CREATE INDEX idx_image_assets_create_time ON image_assets (create_time DESC);
